export const START_PENDING = 'START_PENDING'
export const START_SUCCESS = 'START_SUCCESS'
export const START_ERROR = 'START_ERROR'
export const UPDATE_SUBMIT = 'UPDATE_SUBMIT'
export const UPDATE_FIELD = 'UPDATE_FIELD'
export const LOGIN_USER_INFO = 'LOGIN_USER_INFO';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';